// <auto-generated />
namespace Arabjobs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatetablejob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetablejob));
        
        string IMigrationMetadata.Id
        {
            get { return "201903102035311_updatetablejob"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
